#!/bin/csh

echo " "
echo "*************************************************"
echo "* 1) Generate input files for the block ranges. *"
echo "* 2) fit pdf for the block ranges and output    *"
echo "*    polynomials for v-states (not blocks).     *"
echo "*************************************************"
echo "  The polynomial order is set for each block (v-state) "
echo "  But be careful when changes the order. "
echo " "

  head -1 ../current_situation > aaa
  set mdn = `more aaa`
  rm aaa
  head -2 ../current_situation > aaa
  tail -1 aaa > bbb
  set nvs = `more bbb`
  rm aaa bbb

  echo " "
  echo  MD No. =  ${mdn}
  echo  N. of v states =  ${nvs}
  echo "  "

  set paras = " -120000.0   50.0 "
  echo " fitting ragne parameters:" $paras "   <-------  OK? "
  echo "      The parameters are put in the first line of inp_fit.dat_b*."

  echo "  "
  echo " May I proceed? "
  echo " If OK, input 1.  If No, input any number else 1. "

  set ok = $<
  if( $ok == 1) then
     echo " OK. I proceed. "
     goto p1 
  endif
  echo " I stop here. "
  echo " "
  exit
#*************************************
p1:

  set dir = md${mdn}

  @ ii = 1
  while( $ii <= $nvs )

    @ iord = 8
    if($ii == 1 ) @ iord = 8
    if($ii == 2 ) @ iord = 8
    if($ii == 3 ) @ iord = 9
    if($ii == 4 ) @ iord = 9
    if($ii == 5 ) @ iord = 9
    if($ii == 6 ) @ iord = 9   
    if($ii == 7 ) @ iord = 9   

    echo "V st = " $ii " iord = " $iord 
    echo "      Please check if fitting is OK. "

# 1) Generate inp_fit.dat for block.

    set work1 = `more ${dir}/range.b${ii} `
    set work2 = `more ${dir}/range.s${ii} `

    echo ${paras}  "  999.0  0.0 " $iord " 0.0" > aaa1
    echo $work1  $work2 > aaa2
    echo $work1 > aaa3
    
    cat aaa1 aaa2 aaa3 ${dir}/entire.pdf  > ${dir}/inp_fit.dat_b${ii}

# 2) Do fitting for the block ranges and 
#    output polynomials for v-states (not blocks). 

    src_pre/aho.exe < ${dir}/inp_fit.dat_b${ii}

    mv fort.11 ${dir}/b${ii}.fort.11
    mv fort.12 ${dir}/b${ii}.fort.12
    mv fort.20 ${dir}/b${ii}.fort.20

    rm fort.* aaa*

    @ ii ++
  end
#*************************************
exit

